import type { LocalPlace } from "@/types/city";
export const localPlaces: LocalPlace[] = [
  // Red Line
  { id: "miyapur_bus",         name: "Miyapur Bus Terminus",                    category: "transport",  coordinates: [17.4950, 78.362], nearestStationId: "miyapur",          distanceKm: 0.1  },
  { id: "jntu_campus",         name: "JNTU Hyderabad Campus",                  category: "education",  coordinates: [17.4935, 78.374], nearestStationId: "jntu_college",      distanceKm: 0.1  },
  { id: "kukatpally_market",   name: "Kukatpally Market (Y Junction)",          category: "shopping",   coordinates: [17.4848, 78.398], nearestStationId: "kukatpally",       distanceKm: 0.1  },
  { id: "bhel_township",       name: "BHEL Township, Hyderabad",               category: "civic",      coordinates: [17.4488, 78.438], nearestStationId: "bhel",             distanceKm: 0.1  },
  { id: "begumpet_airport_old","name":"Begumpet (Old Airport / HAL)",           category: "transport",  coordinates: [17.4418, 78.467], nearestStationId: "begumpet",         distanceKm: 0.1  },
  { id: "ameerpet_market",     name: "Ameerpet Market & IT Hub",               category: "shopping",   coordinates: [17.4348, 78.453], nearestStationId: "ameerpet",         distanceKm: 0.05 },
  { id: "nampally_station",    name: "Hyderabad Deccan Railway Station",        category: "transport",  coordinates: [17.4028, 78.476], nearestStationId: "nampally",         distanceKm: 0.1  },
  { id: "charminar",           name: "Charminar (UNESCO Tentative)",            category: "heritage",   coordinates: [17.3616, 78.4747], nearestStationId: "mg_bus_station",  distanceKm: 1.8  },
  { id: "mg_bus_stand",        name: "Mahatma Gandhi Bus Station (MGBS)",       category: "transport",  coordinates: [17.3781, 78.480], nearestStationId: "mg_bus_station",   distanceKm: 0.05 },
  { id: "salarjung_museum",    name: "Salar Jung Museum",                      category: "heritage",   coordinates: [17.3713, 78.4811], nearestStationId: "mg_bus_station",  distanceKm: 0.8  },
  { id: "malakpet_market",     name: "Malakpet Market",                        category: "shopping",   coordinates: [17.3748, 78.492], nearestStationId: "malakpet",         distanceKm: 0.05 },
  { id: "dilsuknagar_market",  name: "Dilsukhnagar Market",                    category: "shopping",   coordinates: [17.3578, 78.516], nearestStationId: "dilsuknagar",      distanceKm: 0.05 },
  { id: "lb_nagar_bus",        name: "LB Nagar Bus Terminus",                  category: "transport",  coordinates: [17.3438, 78.544], nearestStationId: "lb_nagar",         distanceKm: 0.1  },
  // Blue Line
  { id: "uppal_market",        name: "Uppal Market",                           category: "shopping",   coordinates: [17.4058, 78.557], nearestStationId: "uppal",            distanceKm: 0.1  },
  { id: "osmania_university",  name: "Osmania University Campus",              category: "education",  coordinates: [17.4133, 78.5264], nearestStationId: "tarnaka",          distanceKm: 1.0  },
  { id: "secunderabad_rly",    name: "Secunderabad Railway Station (Major hub)",category: "transport",  coordinates: [17.4358, 78.499], nearestStationId: "secunderabad_east", distanceKm: 0.2  },
  { id: "paradise_biryani",    name: "Paradise Restaurant (Famous Biryani)",   category: "shopping",   coordinates: [17.4428, 78.490], nearestStationId: "paradise",         distanceKm: 0.05 },
  { id: "punjagutta_market",   name: "Punjagutta Market & Somajiguda",         category: "shopping",   coordinates: [17.4308, 78.446], nearestStationId: "punjagutta",       distanceKm: 0.05 },
  { id: "hussain_sagar",       name: "Hussain Sagar Lake & Tankbund",          category: "park",       coordinates: [17.4239, 78.4738], nearestStationId: "necklace_road",   distanceKm: 0.8  },
  { id: "telangana_secretariat","name":"Telangana Secretariat",                category: "civic",      coordinates: [17.4095, 78.4183], nearestStationId: "assembly",         distanceKm: 0.3  },
  { id: "film_city_hyd",       name: "Ramoji Film City (Worlds Largest)",      category: "park",       coordinates: [17.3247, 78.6816], nearestStationId: "lb_nagar",         distanceKm: 25.0 },
  { id: "cyberabad_hitec",     name: "HITEC City / Cyberabad IT Hub",          category: "civic",      coordinates: [17.4500, 78.3726], nearestStationId: "raidurg",          distanceKm: 2.0  },
  { id: "raidurg_cyberabad",   name: "Raidurg / Mindspace IT Park",            category: "civic",      coordinates: [17.4228, 78.381], nearestStationId: "raidurg",          distanceKm: 0.1  },
  { id: "jubilee_hills_market","name":"Jubilee Hills Market",                  category: "shopping",   coordinates: [17.4138, 78.396], nearestStationId: "jubilee_hills",    distanceKm: 0.1  },
  { id: "khairatabad_temple",  name: "Khairatabad Ganesha Temple",             category: "religious",  coordinates: [17.4158, 78.432], nearestStationId: "khairatabad",      distanceKm: 0.05 },
  // Green Line
  { id: "jbs_bus_station",     name: "Jubilee Bus Station (JBS)",              category: "transport",  coordinates: [17.4508, 78.503], nearestStationId: "jbs_parade_ground", distanceKm: 0.05 },
  { id: "secunderabad_west_rly","name":"Secunderabad West Railway Station",    category: "transport",  coordinates: [17.4388, 78.499], nearestStationId: "secunderabad_west", distanceKm: 0.1  },
  { id: "gandhi_hospital_bldg","name":"Gandhi General Hospital",               category: "hospital",   coordinates: [17.4258, 78.492], nearestStationId: "gandhi_hospital",  distanceKm: 0.05 },
  { id: "sultan_bazar_market", name: "Sultan Bazar Market (Textiles)",         category: "shopping",   coordinates: [17.3808, 78.480], nearestStationId: "sultan_bazar",     distanceKm: 0.05 },
  { id: "golconda_fort",       name: "Golconda Fort (UNESCO Tentative)",       category: "heritage",   coordinates: [17.3833, 78.4011], nearestStationId: "filmnagar",        distanceKm: 5.5  },
  { id: "birla_mandir_hyd",    name: "Birla Mandir (Naubat Pahad)",            category: "religious",  coordinates: [17.4098, 78.4619], nearestStationId: "lakdi_ka_pul",     distanceKm: 0.8  },
  { id: "birla_planetarium",   name: "Birla Planetarium & Science Museum",     category: "heritage",   coordinates: [17.4093, 78.4606], nearestStationId: "lakdi_ka_pul",     distanceKm: 0.9  },
  { id: "nehru_zoo",           name: "Nehru Zoological Park",                  category: "park",       coordinates: [17.3492, 78.4505], nearestStationId: "mg_bus_station",   distanceKm: 3.5  },
  { id: "mecca_masjid",        name: "Mecca Masjid (Historic)",               category: "religious",  coordinates: [17.3601, 78.4736], nearestStationId: "mg_bus_station",   distanceKm: 2.0  },
];
