import type { LocalPlace } from "@/types/city";
export const localPlaces: LocalPlace[] = [
  { id:"marina_beach",        name:"Marina Beach",               category:"park",        coordinates:[13.0569,80.2822], nearestStationId:"government_estate",   distanceKm:1.5 },
  { id:"kapaleeshwarar",      name:"Kapaleeshwarar Temple",      category:"religious",   coordinates:[13.0339,80.2699], nearestStationId:"nandanam",            distanceKm:2.0 },
  { id:"fort_st_george",      name:"Fort St. George",            category:"heritage",    coordinates:[13.0801,80.2872], nearestStationId:"central",             distanceKm:0.8 },
  { id:"egmore_museum",       name:"Government Museum Egmore",   category:"heritage",    coordinates:[13.0697,80.2632], nearestStationId:"kilpauk_medical_college",distanceKm:0.6},
  { id:"vadapalani_murugan",  name:"Vadapalani Murugan Temple",  category:"religious",   coordinates:[13.0512,80.1812], nearestStationId:"vadapalani",          distanceKm:0.2 },
  { id:"express_avenue",      name:"Express Avenue Mall",        category:"shopping",    coordinates:[13.0598,80.2632], nearestStationId:"government_estate",   distanceKm:1.8 },
  { id:"phoenix_marketcity",  name:"Phoenix Marketcity Chennai", category:"shopping",    coordinates:[13.0522,80.2118], nearestStationId:"ekkattuthangal",      distanceKm:0.8 },
  { id:"spencer_plaza",       name:"Spencer Plaza",              category:"shopping",    coordinates:[13.0672,80.2758], nearestStationId:"central",             distanceKm:0.9 },
  { id:"anna_university",     name:"Anna University",            category:"education",   coordinates:[13.0102,80.2352], nearestStationId:"guindy",              distanceKm:1.2 },
  { id:"iit_madras",          name:"IIT Madras",                 category:"education",   coordinates:[12.9916,80.2337], nearestStationId:"guindy",              distanceKm:2.5 },
  { id:"central_railway",     name:"Chennai Central Station",    category:"transport",   coordinates:[13.0827,80.2762], nearestStationId:"central",             distanceKm:0.1 },
  { id:"cmbt_bus_stand",      name:"CMBT Bus Terminus",          category:"transport",   coordinates:[13.0658,80.1912], nearestStationId:"cmbt",                distanceKm:0.1 },
  { id:"chennai_airport_intl",name:"Chennai International Airport",category:"transport", coordinates:[12.9823,80.1637], nearestStationId:"chennai_airport",     distanceKm:0.2 },
  { id:"ripon_buildings",     name:"Ripon Buildings (GMC)",      category:"civic",       coordinates:[13.0812,80.2782], nearestStationId:"central",             distanceKm:0.5 },
  { id:"arignar_anna_zoo_main",name:"Arignar Anna Zoological Park",category:"entertainment",coordinates:[12.8922,80.0558],nearestStationId:"arignar_anna_zoo", distanceKm:0.2},
  { id:"mgr_film_city",       name:"MGR Film City",              category:"entertainment",coordinates:[13.1118,80.2312], nearestStationId:"tiruvottriyur",      distanceKm:2.5},
  { id:"parry_corner",        name:"Parry's Corner Market",      category:"shopping",    coordinates:[13.0858,80.2832], nearestStationId:"high_court",          distanceKm:0.6 },
  { id:"nungambakkam_high_rd",name:"Nungambakkam High Road",     category:"shopping",    coordinates:[13.0588,80.2418], nearestStationId:"thousand_lights",     distanceKm:1.0 },
  { id:"malar_hospital",      name:"Malar Hospital Adyar",       category:"hospital",    coordinates:[13.0022,80.2568], nearestStationId:"alandur",             distanceKm:2.8 },
  { id:"apollo_hospitals",    name:"Apollo Hospitals Greams Rd", category:"hospital",    coordinates:[13.0572,80.2468], nearestStationId:"thousand_lights",     distanceKm:0.8 },
  { id:"valluvar_kottam",     name:"Valluvar Kottam",            category:"heritage",    coordinates:[13.0581,80.2452], nearestStationId:"thousand_lights",     distanceKm:0.6 },
  { id:"birla_planetarium",   name:"Jawaharlal Nehru Planetarium",category:"entertainment",coordinates:[13.0701,80.2512],nearestStationId:"pachaiyappas_college",distanceKm:0.8},
];
